server.port=9000
spring.cloud.consul.discovery.health-check-url=http://127.0.0.1:${server.port}${spring.cloud.consul.discovery.health-check-path}
spring.security.oauth2.authorizationserver.issuer=${server.oauth2.issuer-uri}
simplepoint.security.oauth2.resource-indicator.allowed-prefixes=${server.public-scheme}://${server.public-host}:8080/mcp/
