package org.simplepoint.plugin.dna.core.service.dialect;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Types;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.simplepoint.plugin.dna.core.api.spi.JdbcDatabaseDialect;
import org.simplepoint.plugin.dna.core.api.spi.JdbcDatabaseDialect.MetadataResult;
import org.simplepoint.plugin.dna.core.api.vo.JdbcMetadataModels;

/**
 * Tests for {@link AbstractJdbcDatabaseDialect} non-abstract methods, exercised via
 * {@link PostgresqlJdbcDatabaseDialect} and {@link GenericJdbcDatabaseDialect}.
 */
class AbstractJdbcDatabaseDialectTest {

  private final PostgresqlJdbcDatabaseDialect pgDialect = new PostgresqlJdbcDatabaseDialect();
  private final GenericJdbcDatabaseDialect genericDialect = new GenericJdbcDatabaseDialect();

  private static JdbcDatabaseDialect.SupportContext pgContext() {
    return new JdbcDatabaseDialect.SupportContext(
        "postgresql", "org.postgresql.Driver", "PostgreSQL", "16",
        "mydb", "public", "\"", Map.of()
    );
  }

  private static JdbcDatabaseDialect.SupportContext genericContext() {
    return new JdbcDatabaseDialect.SupportContext(
        "other", "com.example.Driver", "SomeDB", "1.0",
        null, null, "\"", Map.of()
    );
  }

  // ---- buildCreateTableSql ----

  @Test
  void buildCreateTableSqlShouldProduceCorrectStatement() {
    String sql = pgDialect.buildCreateTableSql(
        "\"mydb\".\"users\"",
        List.of(
            new JdbcMetadataModels.ColumnDefinition("id", "BIGINT", null, null, false, null, true, null),
            new JdbcMetadataModels.ColumnDefinition("name", "VARCHAR", 255, null, true, null, null, null)
        ),
        List.of(new JdbcMetadataModels.ConstraintDefinition(
            "pk_users", JdbcMetadataModels.ConstraintType.PRIMARY_KEY,
            List.of("id"), null, null
        )),
        pgContext()
    );
    assertTrue(sql.startsWith("CREATE TABLE \"mydb\".\"users\" ("));
    assertTrue(sql.contains("\"id\" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
    assertTrue(sql.contains("\"name\" VARCHAR(255)"));
    assertTrue(sql.contains("CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\")"));
  }

  @Test
  void buildCreateTableSqlShouldThrowWhenNoColumns() {
    assertThrows(IllegalArgumentException.class, () ->
        pgDialect.buildCreateTableSql("\"t\"", List.of(), List.of(), pgContext())
    );
  }

  @Test
  void buildCreateTableSqlNullConstraintsShouldSucceed() {
    String sql = pgDialect.buildCreateTableSql(
        "\"t\"",
        List.of(new JdbcMetadataModels.ColumnDefinition("id", "INT", null, null, false, null, null, null)),
        null
    );
    assertEquals("CREATE TABLE \"t\" (\"id\" INT NOT NULL)", sql);
  }

  // ---- buildCreateViewSql ----

  @Test
  void buildCreateViewSqlShouldProduceCorrectStatement() {
    String sql = pgDialect.buildCreateViewSql("\"mydb\".\"v_users\"", "SELECT * FROM users");
    assertEquals("CREATE VIEW \"mydb\".\"v_users\" AS SELECT * FROM users", sql);
  }

  // ---- buildAddColumnSql ----

  @Test
  void buildAddColumnSqlShouldProduceAlterTableStatement() {
    String sql = pgDialect.buildAddColumnSql(
        "\"mydb\".\"users\"",
        new JdbcMetadataModels.ColumnDefinition("email", "VARCHAR", 512, null, true, null, null, null),
        pgContext()
    );
    assertEquals("ALTER TABLE \"mydb\".\"users\" ADD COLUMN \"email\" VARCHAR(512)", sql);
  }

  // ---- buildAlterColumnSql (standard rename + type change) ----

  @Test
  void buildAlterColumnSqlShouldGenerateRenameAndTypeStatements() {
    List<String> sqls = pgDialect.buildAlterColumnSql(
        "\"t\"", "old_col",
        new JdbcMetadataModels.ColumnDefinition("new_col", "TEXT", null, null, true, null, null, null),
        pgContext()
    );
    assertEquals(4, sqls.size());
    assertTrue(sqls.get(0).contains("RENAME COLUMN \"old_col\" TO \"new_col\""));
    assertTrue(sqls.get(1).contains("ALTER COLUMN \"new_col\" TYPE TEXT"));
    assertTrue(sqls.get(2).contains("DROP DEFAULT"));
    assertTrue(sqls.get(3).contains("DROP NOT NULL"));
  }

  @Test
  void buildAlterColumnSqlWithDefaultAndNotNullShouldSetBoth() {
    List<String> sqls = pgDialect.buildAlterColumnSql(
        "\"t\"", "col",
        new JdbcMetadataModels.ColumnDefinition("col", "INT", null, null, false, "0", null, null),
        pgContext()
    );
    assertTrue(sqls.stream().anyMatch(s -> s.contains("SET DEFAULT 0")));
    assertTrue(sqls.stream().anyMatch(s -> s.contains("SET NOT NULL")));
  }

  // ---- buildDropConstraintSql (standard) ----

  @Test
  void buildDropConstraintSqlShouldProduceDropConstraintStatement() {
    String sql = pgDialect.buildDropConstraintSql(
        "\"t\"", "uk_email", JdbcMetadataModels.ConstraintType.UNIQUE, pgContext()
    );
    assertEquals("ALTER TABLE \"t\" DROP CONSTRAINT \"uk_email\"", sql);
  }

  // ---- buildAddConstraintSql ----

  @Test
  void buildAddConstraintSqlShouldProduceAlterTableAddStatement() {
    String sql = pgDialect.buildAddConstraintSql(
        "\"t\"",
        new JdbcMetadataModels.ConstraintDefinition(
            "uk_email", JdbcMetadataModels.ConstraintType.UNIQUE, List.of("email"), null, null
        ),
        pgContext()
    );
    assertEquals("ALTER TABLE \"t\" ADD CONSTRAINT \"uk_email\" UNIQUE (\"email\")", sql);
  }

  // ---- constraintDefinition: CHECK and FOREIGN_KEY ----

  @Test
  void buildCreateTableSqlShouldIncludeCheckConstraint() {
    String sql = pgDialect.buildCreateTableSql(
        "\"t\"",
        List.of(new JdbcMetadataModels.ColumnDefinition("score", "INT", null, null, false, null, null, null)),
        List.of(new JdbcMetadataModels.ConstraintDefinition(
            "chk_score", JdbcMetadataModels.ConstraintType.CHECK,
            List.of(), null, "score > 0"
        )),
        pgContext()
    );
    assertTrue(sql.contains("CONSTRAINT \"chk_score\" CHECK (score > 0)"));
  }

  @Test
  void buildCreateTableSqlShouldIncludeForeignKeyConstraint() {
    List<JdbcMetadataModels.PathSegment> tablePath = List.of(
        new JdbcMetadataModels.PathSegment(JdbcMetadataModels.NodeType.SCHEMA, "public"),
        new JdbcMetadataModels.PathSegment(JdbcMetadataModels.NodeType.TABLE, "roles")
    );
    String sql = pgDialect.buildCreateTableSql(
        "\"t\"",
        List.of(new JdbcMetadataModels.ColumnDefinition("role_id", "BIGINT", null, null, false, null, null, null)),
        List.of(new JdbcMetadataModels.ConstraintDefinition(
            "fk_role", JdbcMetadataModels.ConstraintType.FOREIGN_KEY,
            List.of("role_id"),
            new JdbcMetadataModels.ConstraintReference(tablePath, List.of("id")),
            null
        )),
        pgContext()
    );
    assertTrue(sql.contains("CONSTRAINT \"fk_role\" FOREIGN KEY (\"role_id\") REFERENCES"));
    assertTrue(sql.contains("\"public\".\"roles\""));
  }

  // ---- buildCreateNamespaceSql / buildDropNamespaceSql (Schema type via base) ----

  @Test
  void buildCreateNamespaceSqlSchemaShouldUseCreateSchema() {
    // Delegate to base class (PostgreSQL overrides DATABASE only)
    String sql = pgDialect.buildCreateNamespaceSql(JdbcMetadataModels.NodeType.SCHEMA, "analytics", pgContext());
    assertEquals("CREATE SCHEMA \"analytics\"", sql);
  }

  @Test
  void buildDropNamespaceSqlSchemaShouldUseDropSchema() {
    String sql = pgDialect.buildDropNamespaceSql(JdbcMetadataModels.NodeType.SCHEMA, "analytics", true, pgContext());
    assertEquals("DROP SCHEMA \"analytics\" CASCADE", sql);
  }

  @Test
  void buildDropNamespaceSqlSchemaWithoutCascade() {
    String sql = pgDialect.buildDropNamespaceSql(JdbcMetadataModels.NodeType.SCHEMA, "analytics", false, pgContext());
    assertEquals("DROP SCHEMA \"analytics\"", sql);
  }

  @Test
  void buildCreateNamespaceSqlWithUnsupportedTypeShouldThrow() {
    assertThrows(UnsupportedOperationException.class, () ->
        genericDialect.buildCreateNamespaceSql(JdbcMetadataModels.NodeType.TABLE, "t", genericContext())
    );
  }

  // ---- columnTypeSql ----

  @Test
  void columnTypeSqlShouldIncludeSizeAndScale() {
    String sql = pgDialect.buildCreateTableSql(
        "\"t\"",
        List.of(new JdbcMetadataModels.ColumnDefinition("amount", "DECIMAL", 10, 2, false, null, null, null)),
        List.of()
    );
    assertTrue(sql.contains("DECIMAL(10,2)"));
  }

  @Test
  void columnTypeSqlShouldIncludeSizeOnly() {
    String sql = pgDialect.buildCreateTableSql(
        "\"t\"",
        List.of(new JdbcMetadataModels.ColumnDefinition("code", "CHAR", 8, null, false, null, null, null)),
        List.of()
    );
    assertTrue(sql.contains("CHAR(8)"));
  }

  // ---- matchesPattern ----

  @Test
  void matchesPatternShouldHandlePercentWildcard() {
    assertTrue(pgDialect.matchesPattern("information_schema", "%schema%"));
    assertFalse(pgDialect.matchesPattern("public", "%schema%"));
  }

  @Test
  void matchesPatternShouldHandleUnderscoreWildcard() {
    assertTrue(pgDialect.matchesPattern("public", "publi_"));
    assertFalse(pgDialect.matchesPattern("public", "privat_"));
  }

  @Test
  void matchesPatternNullPatternShouldAlwaysMatch() {
    assertTrue(pgDialect.matchesPattern("anything", null));
    assertTrue(pgDialect.matchesPattern(null, null));
  }

  @Test
  void matchesPatternNullValueShouldNotMatchNonNullPattern() {
    assertFalse(pgDialect.matchesPattern(null, "pub%"));
  }

  // ---- normalizeTableType ----

  @Test
  void normalizeTableTypeShouldConvertBaseTableToTable() {
    assertEquals("TABLE", pgDialect.normalizeTableType("BASE TABLE"));
    assertEquals("TABLE", pgDialect.normalizeTableType("base table"));
    assertEquals("VIEW", pgDialect.normalizeTableType("VIEW"));
    assertNull(pgDialect.normalizeTableType(null));
    assertNull(pgDialect.normalizeTableType("  "));
  }

  // ---- expandTableTypes ----

  @Test
  void expandTableTypesShouldAddBaseTableWhenTableRequested() {
    String[] types = pgDialect.expandTableTypes(List.of("TABLE", "VIEW"));
    assertNotNull(types);
    List<String> list = List.of(types);
    assertTrue(list.contains("TABLE"));
    assertTrue(list.contains("BASE TABLE"));
    assertTrue(list.contains("VIEW"));
  }

  @Test
  void expandTableTypesNullOrEmptyShouldReturnNull() {
    assertNull(pgDialect.expandTableTypes(null));
    assertNull(pgDialect.expandTableTypes(List.of()));
  }

  // ---- findColumnIndex ----

  @Test
  void findColumnIndexShouldReturnCorrectIndex() {
    List<JdbcDatabaseDialect.MetadataColumn> columns = List.of(
        new JdbcDatabaseDialect.MetadataColumn("TABLE_CAT", "VARCHAR", Types.VARCHAR),
        new JdbcDatabaseDialect.MetadataColumn("TABLE_TYPE", "VARCHAR", Types.VARCHAR)
    );
    assertEquals(1, pgDialect.findColumnIndex(columns, "TABLE_TYPE"));
    assertEquals(0, pgDialect.findColumnIndex(columns, "table_cat"));
    assertEquals(-1, pgDialect.findColumnIndex(columns, "MISSING"));
  }

  // ---- resolveMetadataNamespaceSupport ----

  @Test
  void resolveMetadataNamespaceSupportShouldReturnFalseWhenMetaDataIsNull() throws Exception {
    JdbcDatabaseDialect.MetadataNamespaceSupport support =
        pgDialect.resolveMetadataNamespaceSupport(null, null, pgContext());
    assertFalse(support.supportsCatalogsInTableDefinitions());
    assertFalse(support.supportsSchemasInTableDefinitions());
  }

  @Test
  void resolveMetadataNamespaceSupportShouldDelegateToMetaData() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(true);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);

    JdbcDatabaseDialect.MetadataNamespaceSupport support =
        pgDialect.resolveMetadataNamespaceSupport(null, metaData, pgContext());
    assertTrue(support.supportsCatalogsInTableDefinitions());
    assertFalse(support.supportsSchemasInTableDefinitions());
  }

  // ---- loadCatalogs ----

  @Test
  void loadCatalogsShouldReturnEmptyWhenCatalogsNotSupported() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(false);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);

    MetadataResult result = pgDialect.loadCatalogs(null, metaData, pgContext(), null);
    assertTrue(result.rows().isEmpty());
  }

  @Test
  void loadCatalogsShouldFilterByPatternAndReturnVisibleCatalogs() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(true);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);
    ResultSet catalogResultSet = buildStringResultSet("TABLE_CAT", List.of("mydb", "audit_db", "postgres"));
    when(metaData.getCatalogs()).thenReturn(catalogResultSet);

    MetadataResult result = pgDialect.loadCatalogs(null, metaData, pgContext(), "%db");
    assertEquals(2, result.rows().size());
  }

  // ---- loadSchemas ----

  @Test
  void loadSchemasShouldReturnEmptyWhenSchemasNotSupported() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(false);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);

    MetadataResult result = pgDialect.loadSchemas(null, metaData, pgContext(), null, null);
    assertTrue(result.rows().isEmpty());
  }

  // ---- loadTableTypes ----

  @Test
  void loadTableTypesShouldNormalizeBaseTableToTable() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    ResultSet tableTypesResult = buildStringResultSet("TABLE_TYPE", List.of("BASE TABLE", "VIEW", "TABLE"));
    when(metaData.getTableTypes()).thenReturn(tableTypesResult);

    MetadataResult result = pgDialect.loadTableTypes(null, metaData, pgContext());
    List<String> types = result.rows().stream()
        .map(row -> (String) row.get(0))
        .distinct()
        .toList();
    assertTrue(types.contains("TABLE"));
    assertFalse(types.contains("BASE TABLE"));
  }

  // ---- loadTables ----

  @Test
  void loadTablesShouldPassExpandedTableTypesToMetaData() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(false);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);
    ResultSet emptyResultSet = buildStringResultSet("TABLE_NAME");
    when(metaData.getTables(isNull(), isNull(), eq("%"), any())).thenReturn(emptyResultSet);

    MetadataResult result = pgDialect.loadTables(null, metaData, pgContext(), null, null, null, List.of("TABLE"));
    assertNotNull(result);
  }

  // ---- loadColumns ----

  @Test
  void loadColumnsShouldCallMetaDataGetColumns() throws Exception {
    DatabaseMetaData metaData = mock(DatabaseMetaData.class);
    when(metaData.supportsCatalogsInTableDefinitions()).thenReturn(false);
    when(metaData.supportsSchemasInTableDefinitions()).thenReturn(false);
    ResultSet emptyResultSet = buildStringResultSet("COLUMN_NAME");
    when(metaData.getColumns(isNull(), isNull(), eq("users"), eq("%"))).thenReturn(emptyResultSet);

    MetadataResult result = pgDialect.loadColumns(null, metaData, pgContext(), null, null, "users", null);
    assertNotNull(result);
  }

  // ---- normalizeMetadataCellValue ----

  @Test
  void normalizeMetadataCellValueShouldReturnNullForNull() throws Exception {
    assertNull(pgDialect.normalizeMetadataCellValue(null));
  }

  @Test
  void normalizeMetadataCellValueShouldConvertTimestampToString() throws Exception {
    java.sql.Timestamp ts = new java.sql.Timestamp(System.currentTimeMillis());
    Object result = pgDialect.normalizeMetadataCellValue(ts);
    assertTrue(result instanceof String);
  }

  @Test
  void normalizeMetadataCellValueShouldBase64EncodeBytesArray() throws Exception {
    byte[] bytes = new byte[]{1, 2, 3};
    Object result = pgDialect.normalizeMetadataCellValue(bytes);
    assertTrue(result instanceof String);
    assertEquals(java.util.Base64.getEncoder().encodeToString(bytes), result);
  }

  @Test
  void normalizeMetadataCellValueShouldReturnPrimitiveAsIs() throws Exception {
    assertEquals(42L, pgDialect.normalizeMetadataCellValue(42L));
    assertEquals("hello", pgDialect.normalizeMetadataCellValue("hello"));
  }

  // ---- Generic dialect ----

  @Test
  void genericDialectShouldSupportAllContexts() {
    assertTrue(genericDialect.supports(genericContext()));
    assertEquals("generic", genericDialect.code());
    assertEquals("Generic JDBC", genericDialect.name());
  }

  // ---- qualifyName / quoteIdentifier ----

  @Test
  void qualifyNameShouldBuildCorrectQualifiedName() {
    assertEquals("\"mydb\".\"public\".\"users\"",
        pgDialect.qualifyName("mydb", "public", "users", pgContext()));
    assertEquals("\"public\".\"users\"",
        pgDialect.qualifyName(null, "public", "users", pgContext()));
    assertEquals("\"users\"",
        pgDialect.qualifyName(null, null, "users", pgContext()));
  }

  // ---- Helper builder ----

  private static ResultSet buildStringResultSet(final String... columnNames) throws Exception {
    return buildStringResultSet(columnNames[0], columnNames.length > 1
        ? List.of()
        : List.of());
  }

  private static ResultSet buildStringResultSet(final String columnName, final List<String> values) throws Exception {
    ResultSet rs = mock(ResultSet.class);
    ResultSetMetaData rsMeta = mock(ResultSetMetaData.class);
    when(rs.getMetaData()).thenReturn(rsMeta);
    when(rsMeta.getColumnCount()).thenReturn(1);
    when(rsMeta.getColumnLabel(1)).thenReturn(columnName);
    when(rsMeta.getColumnName(1)).thenReturn(columnName);
    when(rsMeta.getColumnTypeName(1)).thenReturn("VARCHAR");
    when(rsMeta.getColumnType(1)).thenReturn(Types.VARCHAR);

    if (values.isEmpty()) {
      when(rs.next()).thenReturn(false);
    } else {
      Boolean[] trues = new Boolean[values.size()];
      java.util.Arrays.fill(trues, Boolean.TRUE);
      Boolean first = trues[0];
      Boolean[] rest = java.util.Arrays.copyOfRange(trues, 1, trues.length);
      Boolean[] withFalse = new Boolean[values.size() + 1];
      System.arraycopy(trues, 0, withFalse, 0, values.size());
      withFalse[values.size()] = Boolean.FALSE;
      when(rs.next()).thenReturn(withFalse[0], java.util.Arrays.copyOfRange(withFalse, 1, withFalse.length));
      String[] strValues = values.toArray(String[]::new);
      String firstVal = strValues[0];
      String[] restVals = java.util.Arrays.copyOfRange(strValues, 1, strValues.length);
      when(rs.getString(columnName)).thenReturn(firstVal, restVals);
      when(rs.getObject(1)).thenReturn(firstVal, (Object[]) restVals);
    }
    return rs;
  }
}
