server.port=5000
spring.application.name=dna
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB
simplepoint.dna.jdbc.socket.enabled=true
simplepoint.dna.jdbc.socket.port=15432
