spring.cloud.consul.discovery.health-check-url=http://127.0.0.1:${server.port}${spring.cloud.consul.discovery.health-check-path}
spring.security.oauth2.client.provider.simplepoint.issuer-uri=http://127.0.0.1:9000
spring.security.oauth2.client.registration.simplepoint-client.client-name=simplepoint-client
spring.security.oauth2.client.registration.simplepoint-client.client-id=simplepoint-client
spring.security.oauth2.client.registration.simplepoint-client.client-secret=secret
spring.security.oauth2.client.registration.simplepoint-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.simplepoint-client.scope[0]=openid
spring.security.oauth2.client.registration.simplepoint-client.scope[1]=profile
spring.security.oauth2.client.registration.simplepoint-client.scope[2]=roles
spring.security.oauth2.client.registration.simplepoint-client.scope[3]=tenant
spring.security.oauth2.client.registration.simplepoint-client.scope[4]=organs
spring.security.oauth2.client.registration.simplepoint-client.scope[5]=email
spring.security.oauth2.client.registration.simplepoint-client.scope[6]=address
spring.security.oauth2.client.registration.simplepoint-client.scope[7]=phone
spring.security.oauth2.client.registration.simplepoint-client.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/oidc
spring.security.oauth2.client.registration.simplepoint-client.provider=simplepoint