export type RuntimeServer = {
  id: string;
  name?: string;
  code?: string;
  deploymentType?: string;
  transportType?: string;
  status?: string;
  enabled?: boolean;
};
export type RuntimeSecret = {
  id: string;
  scopeType?: string;
  tenantId?: string;
  code: string;
  name: string;
  description?: string;
  hasValue?: boolean;
  enabled?: boolean;
  rotatedAt?: string;
};

export type RuntimePool = {
  id: string;
  scopeType?: string;
  tenantId?: string;
  code: string;
  name: string;
  serverId: string;
  imageReference: string;
  imageDigest: string;
  requestedMemoryBytes: number;
  requestedNanoCpus: number;
  requestedPidsLimit: number;
  networkMode: string;
  egressAllowlist?: string[];
  secretIds?: string[];
  minReplicas: number;
  maxReplicas: number;
  desiredReplicas: number;
  activationReplicas: number;
  prewarmNodes: number;
  idleTimeoutSeconds: number;
  replicaLifetimeSeconds: number;
  currentReplicas: number;
  readyReplicas: number;
  prewarmedNodes: number;
  status: string;
  lastActivityAt?: string;
  lastReconciledAt?: string;
  lastPrewarmAt?: string;
  lastError?: string;
};

export type RuntimeWorkload = {
  id: string;
  scopeType?: string;
  tenantId?: string;
  executionId: string;
  serverId: string;
  poolId?: string;
  replicaSequence?: number;
  imageReference: string;
  imageDigest: string;
  requestedMemoryBytes: number;
  requestedNanoCpus: number;
  requestedPidsLimit: number;
  timeoutSeconds: number;
  networkMode: string;
  egressAllowlist?: string[];
  secretIds?: string[];
  status: string;
  assignedNodeId?: string;
  leaseId?: string;
  fencingToken: number;
  runtimeWorkloadId?: string;
  containerId?: string;
  deadlineAt?: string;
  startedAt?: string;
  finishedAt?: string;
  lastObservedAt?: string;
  lastError?: string;
};

export type RuntimeNode = {
  id: string;
  nodeId: string;
  instanceId: string;
  generation: number;
  displayName: string;
  advertiseUrl: string;
  runtimeVersion: string;
  engineApiVersion: string;
  engineOsType: string;
  cpuCores: number;
  memoryBytes: number;
  maxWorkloads: number;
  runningWorkloads: number;
  maxWorkloadMemoryBytes: number;
  maxWorkloadNanoCpus: number;
  maxWorkloadPidsLimit: number;
  requireImageDigest: boolean;
  requireMcpLabels: boolean;
  allowBridgeNetwork: boolean;
  allowEgressNetwork: boolean;
  requireSupplyChainAdmission: boolean;
  seccompEnforced: boolean;
  seccompProfileHash?: string;
  appArmorEnforced: boolean;
  appArmorProfile?: string;
  labels?: Record<string, string>;
  cachedImageDigests?: string[];
  status: string;
  registeredAt?: string;
  lastHeartbeatAt?: string;
  heartbeatExpiresAt?: string;
  lastError?: string;
};

export type RuntimePoolFormValues = {
  code: string;
  name: string;
  serverId: string;
  imageReference: string;
  imageDigest?: string;
  memoryMiB: number;
  cpuCores: number;
  pidsLimit: number;
  networkMode: string;
  egressAllowlist?: string;
  secretIds?: string[];
  minReplicas: number;
  maxReplicas: number;
  desiredReplicas: number;
  activationReplicas: number;
  prewarmNodes: number;
  idleTimeoutSeconds: number;
  replicaLifetimeSeconds: number;
};
