server.public-scheme=${SERVER_PUBLIC_SCHEME:http}
server.public-host=${SERVER_PUBLIC_HOST:127.0.0.1}
simplepoint.security.oauth2.token.audience=simplepoint-api

server.servlet.session.timeout=8h
spring.session.timeout=8h
server.reactive.session.timeout=8h

spring.security.oauth2.client.defaults.require-authorization-consent=true
spring.security.oauth2.client.defaults.require-proof-key=true
spring.security.oauth2.client.defaults.access-token-time-to-live=30m
spring.security.oauth2.client.defaults.refresh-token-time-to-live=8h
spring.security.oauth2.client.defaults.authorization-code-time-to-live=5m
spring.security.oauth2.client.defaults.device-code-time-to-live=5m
spring.security.oauth2.client.defaults.reuse-refresh-tokens=true

spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-interval=10s
spring.cloud.consul.discovery.query-passing=true
spring.cloud.consul.discovery.health-check-critical-timeout=1m
