package org.simplepoint.plugin.ai.workflow.api.model;

/**
 * Append-only Workflow execution event types.
 */
public enum WorkflowExecutionEventType {
  EXECUTION_CREATED,
  EXECUTION_STARTED,
  EXECUTION_PAUSE_REQUESTED,
  EXECUTION_PAUSED,
  EXECUTION_RESUMED,
  EXECUTION_CANCELLED,
  NODE_STARTED,
  NODE_WAITING,
  NODE_SUCCEEDED,
  NODE_FAILED,
  NODE_SKIPPED,
  HUMAN_TASK_CREATED,
  HUMAN_TASK_COMPLETED,
  HUMAN_TASK_TIMED_OUT,
  COMPENSATION_STARTED,
  COMPENSATION_SUCCEEDED,
  COMPENSATION_FAILED,
  EXECUTION_SUCCEEDED,
  EXECUTION_FAILED
}
