id: org.simplepoint.rbac.router.service
name: RBAC Router Service
version: "1.0"
author: simplepoint
description: RBAC resource route and plugin contribution service layer
backend:
  packageScan:
    service: org.simplepoint.plugin.rbac.resource.service.impl,org.simplepoint.plugin.rbac.resource.service.plugin
  instances: {}
