package org.simplepoint.plugin.ai.agent.api.model;

/**
 * Durable, low-cardinality events emitted by one Agent execution.
 */
public enum AgentExecutionEventType {
  EXECUTION_CREATED,
  EXECUTION_STARTED,
  EXECUTION_SUCCEEDED,
  EXECUTION_FAILED,
  EXECUTION_CANCELLED,
  APPROVAL_GRANTED,
  APPROVAL_REJECTED,
  PAUSE_REQUESTED,
  PAUSED,
  RESUMED,
  MODEL_STARTED,
  MODEL_SUCCEEDED,
  MODEL_FAILED,
  SKILL_STARTED,
  SKILL_SUCCEEDED,
  SKILL_FAILED,
  MEMORY_RETRIEVED,
  MEMORY_WRITTEN,
  HUMAN_INTERVENTION_REQUESTED,
  HUMAN_INTERVENTION_WAITING,
  HUMAN_INTERVENTION_COMPLETED,
  HUMAN_INTERVENTION_CANCELLED,
  HUMAN_INTERVENTION_EXPIRED
}
