package org.simplepoint.plugin.ai.core.api.model;

/**
 * Stable, language-neutral provider operation error codes.
 */
public enum AiProviderErrorCode {
  AI_PROVIDER_ID_REQUIRED,
  AI_PROVIDER_NOT_FOUND,
  AI_PROVIDER_DISABLED,
  AI_PROVIDER_REQUEST_INVALID,
  AI_PROVIDER_OPERATION_UNAVAILABLE,
  AI_PROVIDER_RATE_LIMITED,
  AI_PROVIDER_CONNECTION_TEST_FAILED,
  AI_PROVIDER_MODEL_DISCOVERY_FAILED,
  AI_PROVIDER_MODEL_SYNC_FAILED,
  AI_PROVIDER_OPERATION_FAILED
}
