/*
 * Copyright (c) 2025 Jinxu Liu or Organization
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://www.apache.org/licenses/LICENSE-2.0
 */

package org.simplepoint.core.generator;

import cn.hutool.core.lang.generator.SnowflakeGenerator;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.id.IdentifierGenerator;
import org.simplepoint.core.properties.CoreProperties;

/**
 * An implementation of the IdentifierGenerator interface.
 * This class uses the SnowflakeGenerator to generate unique identifiers based
 * on worker and datacenter IDs configured in CoreProperties.
 */
public class SnowflakeIdGenerator implements IdentifierGenerator {

  // Static instance of SnowflakeGenerator initialized with worker ID and datacenter ID
  private static final SnowflakeGenerator generator =
      new SnowflakeGenerator(CoreProperties.workerId, CoreProperties.dcId);

  /**
   * Generates a unique identifier using the Snowflake algorithm.
   *
   * @param sharedSessionContractImplementor the session contract implementor
   * @param o                                the entity object for which the ID is being generated
   * @return a unique identifier generated by SnowflakeGenerator
   */
  @Override
  public Object generate(SharedSessionContractImplementor sharedSessionContractImplementor,
                         Object o) {
    return generator.next();
  }
}

