package org.simplepoint.plugin.dna.jdbc.driver;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Concrete {@link Statement} implementation for the DNA JDBC driver.
 *
 * <p>This class replaces the former dynamic-proxy {@code StatementHandler} that
 * was generated inside {@link DnaJdbcProxies}.  It is intentionally
 * <strong>not</strong> {@code final} so that {@code DnaJdbcPreparedStatement}
 * can extend it with parameter-binding logic.
 *
 * <p>Only read queries are supported; any mutation or batch operation throws
 * {@link SQLFeatureNotSupportedException}.
 */
class DnaJdbcStatement implements Statement {

  protected final DnaJdbcConnection connection;

  private final int resultSetType;

  private final int resultSetConcurrency;

  private final int resultSetHoldability;

  private boolean closed;

  private int maxRows;

  private int queryTimeout;

  private int fetchSize;

  private boolean closeOnCompletion;

  protected ResultSet currentResultSet;

  DnaJdbcStatement(
      final DnaJdbcConnection connection,
      final int resultSetType,
      final int resultSetConcurrency,
      final int resultSetHoldability
  ) {
    this.connection = connection;
    this.resultSetType = resultSetType;
    this.resultSetConcurrency = resultSetConcurrency;
    this.resultSetHoldability = resultSetHoldability;
  }

  // ------------------------------------------------------------------
  // Protected helpers for subclasses
  // ------------------------------------------------------------------

  /**
   * Executes the given SQL query against the DNA gateway and returns the
   * resulting {@link ResultSet}.  Any previously open result set is closed
   * first.
   *
   * @param sql the SQL query to execute (must not be {@code null})
   * @return the query result set
   * @throws SQLException if a database access error occurs
   */
  protected ResultSet doExecuteQuery(final String sql) throws SQLException {
    closeCurrentResultSet();
    DnaJdbcModels.QueryResult result =
        connection.client().query(connection.currentCatalog(), sql, connection.currentSchema());
    currentResultSet = ResultSetBuilder.fromQueryResult(result, maxRows);
    return currentResultSet;
  }

  /**
   * Closes the currently held result set, if any.
   *
   * @throws SQLException if closing the result set fails
   */
  protected void closeCurrentResultSet() throws SQLException {
    if (currentResultSet != null) {
      currentResultSet.close();
      currentResultSet = null;
    }
  }

  /**
   * Throws {@link SQLException} if this statement or its parent connection is
   * already closed.
   *
   * @throws SQLException if this statement is closed
   */
  protected void ensureOpen() throws SQLException {
    if (closed) {
      throw new SQLException("Statement 已关闭");
    }
    if (connection.isClosed()) {
      throw new SQLException("DNA JDBC 连接已关闭");
    }
  }

  /**
   * Resolves the SQL string to execute for a plain {@link Statement}.
   * Subclasses may override to support prepared-statement template rendering.
   *
   * @param sql the explicit SQL passed by the caller (may be {@code null})
   * @return the trimmed, non-null SQL string
   * @throws SQLException if the resolved SQL is blank or {@code null}
   */
  protected String resolveSql(final String sql) throws SQLException {
    String normalized = trimToNull(sql);
    if (normalized == null) {
      throw new SQLException("SQL 不能为空");
    }
    return normalized;
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — query execution
  // ------------------------------------------------------------------

  @Override
  public ResultSet executeQuery(final String sql) throws SQLException {
    ensureOpen();
    return doExecuteQuery(resolveSql(sql));
  }

  @Override
  public boolean execute(final String sql) throws SQLException {
    ensureOpen();
    doExecuteQuery(resolveSql(sql));
    return true;
  }

  @Override
  public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(final String sql, final String[] columnNames) throws SQLException {
    return execute(sql);
  }

  @Override
  public int executeUpdate(final String sql) throws SQLException {
    ensureOpen();
    throw unsupported("更新语句");
  }

  @Override
  public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(final String sql) throws SQLException {
    ensureOpen();
    throw unsupported("更新语句");
  }

  @Override
  public long executeLargeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
    return executeLargeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
    return executeLargeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(final String sql, final String[] columnNames) throws SQLException {
    return executeLargeUpdate(sql);
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — batch operations (unsupported)
  // ------------------------------------------------------------------

  @Override
  public void addBatch(final String sql) throws SQLException {
    ensureOpen();
    throw unsupported("addBatch");
  }

  @Override
  public int[] executeBatch() throws SQLException {
    ensureOpen();
    throw unsupported("executeBatch");
  }

  @Override
  public long[] executeLargeBatch() throws SQLException {
    ensureOpen();
    throw unsupported("executeLargeBatch");
  }

  @Override
  public void clearBatch() throws SQLException {
    // no-op
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — result access
  // ------------------------------------------------------------------

  @Override
  public ResultSet getResultSet() throws SQLException {
    ensureOpen();
    return currentResultSet;
  }

  @Override
  public int getUpdateCount() throws SQLException {
    ensureOpen();
    return -1;
  }

  @Override
  public long getLargeUpdateCount() throws SQLException {
    ensureOpen();
    return -1L;
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    ensureOpen();
    return false;
  }

  @Override
  public boolean getMoreResults(final int current) throws SQLException {
    ensureOpen();
    return false;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    ensureOpen();
    return ResultSetBuilder.emptyResultSet();
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — result set properties
  // ------------------------------------------------------------------

  @Override
  public int getResultSetType() throws SQLException {
    return resultSetType;
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return resultSetConcurrency;
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return resultSetHoldability;
  }

  @Override
  public void setFetchDirection(final int direction) throws SQLException {
    // no-op
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return ResultSet.FETCH_FORWARD;
  }

  @Override
  public void setFetchSize(final int rows) throws SQLException {
    this.fetchSize = rows;
  }

  @Override
  public int getFetchSize() throws SQLException {
    return fetchSize;
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — row / timeout / field limits
  // ------------------------------------------------------------------

  @Override
  public void setMaxRows(final int max) throws SQLException {
    this.maxRows = max;
  }

  @Override
  public int getMaxRows() throws SQLException {
    return maxRows;
  }

  @Override
  public void setLargeMaxRows(final long max) throws SQLException {
    this.maxRows = (int) max;
  }

  @Override
  public long getLargeMaxRows() throws SQLException {
    return (long) maxRows;
  }

  @Override
  public void setQueryTimeout(final int seconds) throws SQLException {
    this.queryTimeout = seconds;
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return queryTimeout;
  }

  @Override
  public void setMaxFieldSize(final int max) throws SQLException {
    // no-op
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return 0;
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — lifecycle
  // ------------------------------------------------------------------

  @Override
  public void close() throws SQLException {
    closeCurrentResultSet();
    closed = true;
  }

  @Override
  public boolean isClosed() throws SQLException {
    return closed;
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    this.closeOnCompletion = true;
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return closeOnCompletion;
  }

  // ------------------------------------------------------------------
  // java.sql.Statement — connection / warnings / misc
  // ------------------------------------------------------------------

  @Override
  public Connection getConnection() throws SQLException {
    return connection;
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    // no-op
  }

  @Override
  public void cancel() throws SQLException {
    // no-op
  }

  @Override
  public void setCursorName(final String name) throws SQLException {
    // no-op
  }

  @Override
  public void setEscapeProcessing(final boolean enable) throws SQLException {
    // no-op
  }

  @Override
  public void setPoolable(final boolean poolable) throws SQLException {
    // no-op
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return false;
  }

  // ------------------------------------------------------------------
  // java.sql.Wrapper
  // ------------------------------------------------------------------

  @Override
  public <T> T unwrap(final Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    throw new SQLException("不支持 unwrap 到 " + iface.getName());
  }

  @Override
  public boolean isWrapperFor(final Class<?> iface) throws SQLException {
    return iface.isInstance(this);
  }

  // ------------------------------------------------------------------
  // Internal utilities
  // ------------------------------------------------------------------

  static String trimToNull(final String value) {
    if (value == null) {
      return null;
    }
    String trimmed = value.trim();
    return trimmed.isEmpty() ? null : trimmed;
  }

  static SQLFeatureNotSupportedException unsupported(final String feature) {
    return new SQLFeatureNotSupportedException("DNA JDBC 驱动暂不支持: " + feature);
  }
}
