# 全局环境切换入口
spring.profiles.active=dev
spring.config.import=consul:

spring.cloud.consul.config.data-key=application.properties
spring.cloud.consul.config.format=properties
spring.cloud.consul.config.prefixes[0]=simplepoint/config
spring.cloud.consul.config.profile-separator=-

spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}