spring.jpa.hibernate.ddl-auto=create-drop

simplepoint.security.users[0].email=simplepoint@mail.com
simplepoint.security.users[0].password=123456
simplepoint.security.users[0].email-verified=true
simplepoint.security.users[0].nickname=Simple Point
simplepoint.security.users[0].super-admin=true