spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

simplepoint.datainitialize.enabled=true
simplepoint.datainitialize.module.system-user.enabled=true
simplepoint.datainitialize.module.i18n-base.enabled=true
simplepoint.datainitialize.module.i18n-messages.enabled=true
simplepoint.datainitialize.module.platform-dictionary.enabled=true
simplepoint.datainitialize.module.platform-dictionary-menu.enabled=true
simplepoint.datainitialize.module.platform-organization-menu.enabled=true

simplepoint.security.users[0].email=simplepoint@mail.com
simplepoint.security.users[0].password=123456
simplepoint.security.users[0].email-verified=true
simplepoint.security.users[0].nickname=Simple Point
simplepoint.security.users[0].super-admin=true
