simplepoint.security.users[0].email=${SIMPLEPOINT_ADMIN_EMAIL:simplepoint@mail.com}
simplepoint.security.users[0].password=${SIMPLEPOINT_ADMIN_PASSWORD:changeme}
simplepoint.security.users[0].email-verified=true
simplepoint.security.users[0].nickname=Simple Point
simplepoint.security.users[0].super-admin=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

simplepoint.platform.bootstrap.enabled=true
simplepoint.platform.bootstrap.fail-fast=true
simplepoint.platform.bootstrap.services[0]=common
simplepoint.platform.bootstrap.contributions.system-user.enabled=true
simplepoint.platform.bootstrap.contributions.i18n-base.enabled=true
simplepoint.platform.bootstrap.contributions.i18n-messages.enabled=true
simplepoint.platform.bootstrap.contributions.i18n-bootstrap-v2.enabled=true
simplepoint.platform.bootstrap.contributions.platform-organization-type-dictionary.enabled=true
