simplepoint.datasource.default-name=postgres
simplepoint.datasource.list[0].name=postgres
simplepoint.datasource.list[0].url=jdbc:postgresql://localhost:5432/simplepoint
simplepoint.datasource.list[0].username=postgres
simplepoint.datasource.list[0].password=postgres
simplepoint.datasource.list[0].driver-class-name=org.postgresql.Driver

spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-interval=10s

simplepoint.amqp.rpc.app-id=${spring.application.name}
simplepoint.amqp.rpc.prefix=simplepoint.arpc.
simplepoint.amqp.rpc.priority=100
simplepoint.amqp.rpc.exchange-name=exchange
simplepoint.amqp.rpc.request-queue-name=${spring.application.name}
simplepoint.amqp.rpc.response-queue-name=reply-to
simplepoint.amqp.rpc.providers.i18n.language=common
simplepoint.amqp.rpc.providers.i18n.message=common
simplepoint.amqp.rpc.providers.security.menu=common
simplepoint.amqp.rpc.providers.security.schema=common
simplepoint.amqp.rpc.providers.security.permission=common
simplepoint.amqp.rpc.providers.remote.data.initialize=common