simplepoint.datasource.default-name=postgres
simplepoint.datasource.list[0].name=postgres
simplepoint.datasource.list[0].url=jdbc:postgresql://localhost:5432/simplepoint
simplepoint.datasource.list[0].username=postgres
simplepoint.datasource.list[0].password=postgres
simplepoint.datasource.list[0].driver-class-name=org.postgresql.Driver

spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-interval=10s

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=250ms
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.multiplier=2
spring.rabbitmq.template.retry.max-interval=2s

simplepoint.amqp.rpc.app-id=${spring.application.name}
simplepoint.amqp.rpc.prefix=simplepoint.arpc.
simplepoint.amqp.rpc.priority=100
simplepoint.amqp.rpc.exchange-name=exchange.direct
simplepoint.amqp.rpc.request-queue-name=${spring.application.name}
simplepoint.amqp.rpc.publisher.confirm-timeout=5000
simplepoint.amqp.rpc.dead-letter.exchange-suffix=.dlx
simplepoint.amqp.rpc.dead-letter.queue-suffix=.dlq
simplepoint.amqp.rpc.listener.concurrency=2
simplepoint.amqp.rpc.listener.max-concurrency=8
simplepoint.amqp.rpc.listener.prefetch=16
simplepoint.amqp.rpc.providers.i18n.language=common
simplepoint.amqp.rpc.providers.i18n.message=common
simplepoint.amqp.rpc.providers.security.menu=common
simplepoint.amqp.rpc.providers.security.user=common
simplepoint.amqp.rpc.providers.security.schema=common
simplepoint.amqp.rpc.providers.saas.tenant=common
simplepoint.amqp.rpc.providers.security.permission=common
simplepoint.amqp.rpc.providers.security.authorization-context=common
simplepoint.amqp.rpc.providers.auditing.error-log=auditing
simplepoint.amqp.rpc.providers.auditing.login-log=auditing
simplepoint.amqp.rpc.providers.auditing.permission-change-log=auditing
simplepoint.amqp.rpc.providers.remote.data.initialize=common
